language: matlab
matlab:
  #- R2014b # <- Earliest which ought to be supported
  - R2017b # <- Developped on this varsion
  #- latest

before_script:
  - which matlab
  - git clone https://github.com/MOxUnit/MOxUnit.git # Get MOxUnit
  - make -C MOxUnit install
  #- matlab -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "disp(path); exit()" # Dump maltab path (just to see)
  #- cat output.log
  #- rm -f output.log

script: 
  - matlab -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "back = cd('./MOxUnit/MOxUnit/'); moxunit_set_path(); cd(back); moxunit_runtests tests -verbose; exit()"
  #- matlab -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "moxunit_runtests tests -verbose; exit()"
  - cat output.log