language: minimal
os: linux

matrix:
  include:
    # Developped on R2017b, ought to work back to at least R2014b,
    # but travis only supports matlab R2020a, and only on linux
    - language: matlab
      matlab: R2020a
      
      # Just clone MOxUnit, dont make install it
      before_script:
        - git clone https://github.com/MOxUnit/MOxUnit.git
      
      script: 
        - matlab -batch 'back=cd("./MOxUnit/MOxUnit/"); moxunit_set_path(); cd(back); moxunit_runtests tests -verbose; exit(double(~ans))'

    - language: minimal

      # Get Octave
      before_install:
        - sudo apt-get install octave

      # Clone and install MOxUnit
      before_script:
        - git clone https://github.com/MOxUnit/MOxUnit.git
        - make -C MOxUnit install

      script:        
        - octave --no-gui --quiet --eval 'moxunit_runtests tests -verbose; exit(double(~ans))'