language: matlab
os:
  - osx
  - windows
matlab:
  #- R2014b # <- Earliest which ought to be supported
  - R2017b # <- Developped on this varsion
  - R2020a

before_script:
  - which matlab # Print matlab path (for debugging)
  - git clone https://github.com/MOxUnit/MOxUnit.git # Get MOxUnit
  - matlab -nojvm -nodisplay -nosplash -nodesktop -wait -r "back=cd('./MOxUnit/MOxUnit/');moxunit_set_path();cd(back);savepath();exit(0)"
  #- make -C MOxUnit install
  #- matlab -nojvm -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "disp(path); exit()" # Dump maltab path (just to see)
  #- cat output.log
  #- rm -f output.log

script: 
  #- matlab -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "back = cd('./MOxUnit/MOxUnit/'); moxunit_set_path(); cd(back); moxunit_runtests tests -verbose; exit()"
  - matlab -nojvm -nodisplay -nosplash -nodesktop -wait -logfile output.log -r "moxunit_runtests tests -verbose; exit()"
  - cat output.log